Updates SDK error codes to use JSON-RPC server error range
modelcontextprotocol/typescript-sdk pull request #103
Opened 2024-12-22 18:44 UTC by sumitesh9

Updates SDK error codes to use the JSON-RPC server error range (-32000 to -32099) instead of arbitrary negative numbers.

## Motivation and Context
The SDK was using arbitrary negative numbers (-1, -2) for custom error codes, which could potentially conflict with application-specific error codes. By restricting SDK errors to the JSON-RPC server error range (-32000 to -32099), we ensure compliance with the specification and leave other ranges available for application usage. This change makes the error handling more standardized and prevents potential conflicts.

## How Has This Been Tested?
- [x] Ran the existing tests
- [x] Added new tests for checking error codes in protocol layer

## Breaking Changes
This may be a breaking change as it modifies error codes that applications might be checking against. Applications that explicitly check for -1 or -2 error codes will need to update their checks to use the new values (-32000 and -32001 respectively).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update

## Checklist

- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [x] I have added appropriate error handling
- [x] I have added or updated documentation as needed

## Additional context
This change aligns with JSON-RPC 2.0 specification's recommendation for implementation-defined server errors. The specification reserves codes -32000 to -32099 for this purpose, making it a natural fit for SDK-generated errors. I've chosen to start at -32000 and -32001, leaving plenty of room for additional SDK error codes in the future while maintaining a clear separation from application-specific error codes.

2024-12-22 19:21 UTC, sumitesh9 commented
Hi, @jspahrsummers let me know if any changes are required in this PR.

2025-01-02 14:29 UTC, jspahrsummers requested changes
Thank you! Conceptually this looks good—just a few concrete suggestions to fix up.

2025-01-02 14:29 UTC, jspahrsummers commented on src/types.ts
> +* @author : Sumitesh Naithani
Please remove this by-line. Your contribution will definitely be in the Git commit log and repository history—we just don't want to end up having annotations like this everywhere in the code. 🙏

2025-01-02 14:29 UTC, jspahrsummers commented on src/types.ts
> +* @note : SDK-specific errors should use the server error range (-32000 to -32099), as per JSON-RPC 2.0 specification.
We're not using a documentation generator that will make use of these kind of @ annotations right now. Can you please reformat as a normal documentation comment?

2025-01-02 14:29 UTC, jspahrsummers commented on src/shared/protocol.test.ts
> +        timeout: 100,
We don't want to perform any waiting in tests, however small, as this will degrade overall testing times:
```suggestion
        timeout: 0,
```

2025-01-03 08:57 UTC, jspahrsummers approved these changes
Thank you for the fixes—looks great!

2025-01-03 08:58 UTC, merged