Fixing Windows, using npx
modelcontextprotocol/typescript-sdk pull request #95
Opened 2024-12-15 11:10 UTC by laopo001

## Motivation and Context
Fixing Windows, using npx command

## How Has This Been Tested?
Yes, I have tested this modification on Windows. 
[cross-spawn](https://www.npmjs.com/package/cross-spawn)  is a very general library, resolve various issues that Node encounters when using spawn on Windows.

## Breaking Changes
No

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update

## Checklist
- [x] I have read the [MCP Documentation](https://modelcontextprotocol.io)
- [x] My code follows the repository's style guidelines
- [x] New and existing tests pass locally
- [ ] I have added appropriate error handling
- [ ] I have added or updated documentation as needed

## Additional context
No

2024-12-15 11:23 UTC, anaisbetts commented
@laopo001 In Claude Desktop, we fix this via spawn-rx which does similar Windows-specific fixups but it might be nice to have this work for other MCP clients

2024-12-16 17:35 UTC, jspahrsummers requested changes
Thanks, this seems useful!

Can you please share the sorts of tests that you ran to verify this works? Even better would be if it's possible to write some automated tests for this somehow. 🙏

2025-02-16 10:15 UTC, dinhphieu commented
Is this fixing this kind of issue? For some reason, on my Windows machine, StdioClientTransport can't seem to find npx anywhere in PATH

```
const githubTransport = new StdioClientTransport({
        command: "npx",
        args: ["-y", "@modelcontextprotocol/server-github"],
        env: {
            GITHUB_PERSONAL_ACCESS_TOKEN: process.env.GITHUB_PERSONAL_ACCESS_TOKEN!
        }
    });
```

```
Error: spawn npx ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [ '-y', '@modelcontextprotocol/server-github' ]
}
```

2025-03-24 04:00 UTC, zhibisora commented
I added a test for this pr in https://github.com/modelcontextprotocol/typescript-sdk/pull/198

Can someone go there to have a review?

2025-03-25 12:05 UTC, laopo001 commented
What else do I need to do?

2025-03-25 13:06 UTC, jspahrsummers commented
@laopo001 Please see [my comment above](https://github.com/modelcontextprotocol/typescript-sdk/pull/95#pullrequestreview-2506859982).

2025-03-26 10:15 UTC, closed without merging

2025-03-26 10:15 UTC, jspahrsummers commented
Superseded by https://github.com/modelcontextprotocol/typescript-sdk/pull/198.